CREATE DATABASE IF NOT EXISTS home_garden;

USE home_garden;

CREATE TABLE IF NOT EXISTS usuario (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    apellidos VARCHAR(180) NOT NULL,
    correo VARCHAR(180) NOT NULL,
    pass VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS cultivo (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(180) NOT NULL,
    tipo VARCHAR(80) NOT NULL,
    dificultad CHAR(10) NOT NULL,
    descripcion VARCHAR(280) NOT NULL,
    consejos VARCHAR(280) NOT NULL
);

CREATE TABLE IF NOT EXISTS sensor(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idUsuario INT NOT NULL,
    nombre VARCHAR(180),
    FOREIGN KEY(idUsuario) REFERENCES usuario(id)
);

CREATE TABLE IF NOT EXISTS huerto (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    idSensor INT NOT NULL,
    idCultivo INT NOT NULL,
    FOREIGN KEY(idSensor) REFERENCES sensor(id),
    FOREIGN KEY(idCultivo) REFERENCES cultivo(id)
);
